FROM apache/airflow:3.1.1-python3.13 AS base

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

FROM base AS base-deps
RUN pip install --no-cache-dir --upgrade setuptools
RUN pip install --no-cache-dir uv

FROM base-deps AS python-deps
COPY pyproject.toml uv.lock /tmp/
WORKDIR /tmp
ENV UV_HTTP_TIMEOUT=300

RUN uv pip install --no-cache --group airflow-core --group core

RUN uv pip install --no-cache --group ml

FROM python-deps AS app

WORKDIR /opt/airflow/project
COPY core/ ./core/
COPY modules/ ./modules/

ENV PYTHONPATH=/opt/airflow/project